### ISSUE TITLE
Link to notebook app on git error?

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbinteract#10]
When nbinteract displays an error, students might be left wondering how to proceed. I think we need to provide a link to the user's notebook server when this happens. Something like the image below. Thoughts?
![screen shot 2017-01-25 at 3 25 33 pm](https://cloud.githubusercontent.com/assets/10248125/22313673/9961ac34-e312-11e6-8a1e-ceee74813ce2.png)

**Comment by SaladRaider** [comment]
This looks like a good idea. I can make the link configurable through an env var like ERROR_REDIRECT_URL or something like that, but I'll make the default the datahub link. Would this work?

**Comment by ryanlovett** [comment]
I think the env var is a good idea since it would give other admins the opportunity to point at documentation or some such. Can the default be the hub's base_url rather than datahub specifically?

Here's an example when baseurl is in the javascript:
https://github.com/ryanlovett/nbrsessionproxy/blob/master/nbrsessionproxy/static/tree.js#L8

**Comment by SaladRaider** [comment]
Sure, yeah. That's probably a better idea. So maybe, if the env variable is not specified, a javascript script can default to the hub's base url, like you mentioned.

**Comment by ryanlovett** [comment]
Sounds good to me, thanks!


Ryan

**Comment by SaladRaider** [comment]
OK, I made the changes to Interact. If ERROR_REDIRECT_URL is set, it will use that link. ERROR_REDIRECT_URL must have either 'http://' or 'https://' included. If it is not set, it will just use a link of the hub's base url.

**Comment by ryanlovett** [comment]
Sweet, thanks!


Ryan
