### ISSUE TITLE
Rename or omit "Data8 Interact Server" header

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbinteract#12]
https://github.com/data-8/nbinteract/blob/master/nbinteract/static/progress.html#L5

nbinteract pulls from the data-8 github repository but does not always pull to data8.berkeley.edu. I think this header should be more generic.

- Notebook Puller
- Pulling Files
- Copying Files
- others?

Or omit the header altogether which I favor.

**Comment by allanlwu** [comment]
Changed header from "Data8 Interact Server" to "Jupyter Interact Server."
