### ISSUE TITLE
Pull from branches other than gh-pages

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbinteract#14]
Perhaps via a branch query string parameter or using '@<branch>'.

**Comment by fatmai** [comment]
Thanks, @ryanlovett. This would be great. So we can build interact links for the webpages from our previous connectors (Fall16, etc.) that pulls from the previous term's branch.

**Comment by choldgraf** [comment]
this would be a good idea to ensure robustness of class materials over time. e.g., the history connector which has a new instructor this year
