### ISSUE TITLE
Old way of specifying multiple files doesn't work anymore

### ISSUE THREAD

**Issue by papajohn** [data-8/nbinteract#20]
It's important to specify multiple files in some cases, such as a data file and a notebook. Links from the textbook have the following form:

```
http://datahub.berkeley.edu/user-redirect/interact?repo=textbook&path=notebooks/trip.csv&path=notebooks/station.csv&path=notebooks/Bike_Sharing_in_the_Bay_Area.ipynb
```

originally, this link would load multiple files---`notebooks/trip.csv`, `notebooks/station.csv`, and `notebooks/Bike_Sharing_in_the_Bay_Area.ipynb`---but now it causes an error. Looks like the delimiters are being purged instead of split.

```
File or directory notebooks/trip.csv/notebooks/station.csv/notebooks/Bike_Sharing_in_the_Bay_Area.ipynb
```

**Comment by allanlwu** [comment]
Fixed bug that prevented loading of multiple files.

**Comment by papajohn** [comment]
Thanks, Allan! Can you let me know when it's deployed to
datahub.berkeley.edu so that I can check the textbook links?

**Comment by allanlwu** [comment]
It's been deployed and should be working now!

**Comment by papajohn** [comment]
Works great for the textbook. Thanks!
