### ISSUE TITLE
Error: Sparse checkout leaves no entry on working directory

### ISSUE THREAD

**Issue by ryanlovett** [data-8/nbinteract#9]
I'm trying to find a working interact URL for the stat89a connector. I tried:

 - http://datahub-dev.berkeley.edu/user-redirect/interact?repo=stat89a&path=helloworld.ipynb
 - http://datahub-dev.berkeley.edu/user-redirect/interact?repo=stat89a&path=stat89a/helloworld.ipynb

but nbinteract tells me: `'error: Sparse checkout leaves no entry on working directory'`.

I've verified that the notebook is available in the gh-pages branch of https://github.com/data-8/stat89a.

If I proceed to my notebook app by manually changing the URL, I see that the repository has been pulled and the helloworld.ipynb file is available.

**Comment by SaladRaider** [comment]
I think the reason it's not working is because the file in the stat89a repo is actually called 'helloword.ipynb', but not 'helloworld.ipynb'.

**Comment by ryanlovett** [comment]
Geez, sorry about that Peter!

Can that be checked for, and then report by the status message?

**Comment by SaladRaider** [comment]
Haha, no problem.

Yeah, I think Interact can do something like `git cat-file -e origin/gh-pages:<file name>` to figure out if the file or directory exists. If not, it can say so in the status message.

**Comment by ryanlovett** [comment]
That'd be great!


Ryan

**Comment by SaladRaider** [comment]
OK, I am done making the changes. If someone tries to pull in a file or a directory that doesn't exist in the origin repo, Interact will tell the user.

**Comment by ryanlovett** [comment]
Awesome, I'll try it on datahub-dev tonight probably.


Ryan
